### ISSUE TITLE
Como utilizar

### ISSUE THREAD

**Issue by filipecoelho** [prhost/integracommerce-sdk#8]
Olá, como utilizar e fazer as chamadas pela sua biblioteca.
Parabéns pela iniciativa

**Comment by prhost** [comment]
Fala Felipe,

Cara é bem simples, tenho que criar vergonha na cara e atualizar o README, ja uso ela no dia a dia mas esqueci desse detalhe haha.

Você instala pelo composer `composer require prhost/integracommerce-sdk`

Pra configurar só chamar:

```
use Integracommerce\Classes\IntegraCommerce;

IntegraCommerce::init(
      'usuario',
      'senha',
      true // modo sandbox true ou false
);
```

E ai você chama os endpoints que ta na pasta `src/Endpoints`, exemplo:

```
use Integracommerce\Endpoints\Product as ProductEndpoint;

$productEndpoint = new ProductEndpoint();

$idProduto = 3;
$productModel = $productEndpoint->getProduct($idProduto);
```

Ai os endpoints tem todos os métodos igual na api, get, create, update, etc.
E eles podem retornar uma model do objeto em questão ou uma collection da mesma model se for mais de um item.

Veja se consegue utilizar.

Abraço.
